language: c

cache: apt

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository ppa:terry.guo/gcc-arm-embedded -y
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-arm-none-eabi libpcap-dev libbluetooth-dev libusb-1.0-0-dev
  - wget https://github.com/greatscottgadgets/libbtbb/archive/master.zip
  - unzip master.zip
  - mkdir libbtbb-master/build
  - pushd libbtbb-master/build
  - cmake ..
  - make
  - sudo make install
  - sudo ldconfig
  - popd

script:
  - mkdir host/build
  - pushd host/build
  - CFLAGS="-g -Wall -Wextra -Werror -Wno-zero-length-array" cmake ..
  - make
  - sudo make install
  - sudo ldconfig
  - popd
  - cd firmware
  - make
